### ISSUE TITLE
white background on Reddit dark mode

### ISSUE THREAD

**Issue by SuperStormer** [eritbh/new-reddit-comment-faces#4]
If I turn on Reddit dark mode, the comment face's background still displays as white. 
![Screenshot 2021-09-22 015153](https://user-images.githubusercontent.com/41648788/134290130-5988ebd4-9b72-439b-ab2c-418367062468.png)

This is because the `<body>` tag within the shadow root has `background-color: white` for some reason (reddit being reddit ™️). 

It *should* be fixed if you override it with `background-color: inherit`. If needed, I can make a PR tomorrow.

**Comment by eritbh** [comment]
Thanks for the report, a PR would be more than welcome!
